# Extend CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH so that CMake can find the 
# FindXXX.cmake files generated by conan in the build directory.
set(CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}" ${CMAKE_PREFIX_PATH})

find_package(GTest REQUIRED)
find_package(CURL REQUIRED)
find_library(JSONCPP_LIB NAMES jsoncpp)
find_package(SPDLOG_LIB NAMES spdlog)
find_package(fmt REQUIRED)