get_property(GLOBAL_COMPILE_OPTIONS DIRECTORY PROPERTY COMPILE_OPTIONS)

message( STATUS "------------------------------------------------------------")
message( STATUS "--- System Information --- ")
message( STATUS "HOST System name:      ${CMAKE_HOST_SYSTEM_NAME}")
message( STATUS "HOST System:           ${CMAKE_HOST_SYSTEM}")
message( STATUS "CMake Generator:       ${CMAKE_GENERATOR}")
message( STATUS "CMAKE_BUILD_TYPE:      ${CMAKE_BUILD_TYPE}")
message( STATUS "Compiler info: ${CMAMKE_CXX_COMPILER_ID} (${CMAKE_CXX_COMPILER}); version: ${CMAKE_CXX_COMPILER_VERSION}")
message( STATUS "CMAKE_SOURCE_DIR:      ${CMAKE_SOURCE_DIR}")
message( STATUS "CMAKE_BINARY_DIR:      ${CMAKE_BINARY_DIR}")
message( STATUS "")
message( STATUS " --- Compiler flags ---")
message( STATUS "General:               ${CMAKE_CXX_FLAGS}")
message( STATUS "Debug:                 ${CMAKE_CXX_FLAGS_DEBUG}")
message( STATUS "Release:               ${CMAKE_CXX_FLAGS_RELEASE}")
message( STATUS "RelWithDebInfo:        ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
message( STATUS "MinSizeRel:            ${CMAKE_CXX_FLAGS_MINSIZEREL}")
message( STATUS "compile_options:       ${GLOBAL_COMPILE_OPTIONS}")
message( STATUS "")